// <auto-generated />
using System;
using Biblioteca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biblioteca.Models.Categoria", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.ToTable("Categorias");
            });

            modelBuilder.Entity("Biblioteca.Models.Usuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Email").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<string>("Nome").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Role").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("SenhaHash").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("Biblioteca.Models.Livro", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Titulo").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Autor").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<int>("AnoPublicacao").HasColumnType("int");
                b.Property<int>("CategoriaId").HasColumnType("int");
                b.Property<bool>("Disponivel").HasDefaultValue(true).HasColumnType("bit");
                b.HasKey("Id");
                b.HasIndex("CategoriaId");
                b.ToTable("Livros");
            });

            modelBuilder.Entity("Biblioteca.Models.Emprestimo", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("LivroId").HasColumnType("int");
                b.Property<string>("NomeLeitor").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                b.Property<DateTime>("DataEmprestimo").HasColumnType("datetime2");
                b.Property<DateTime>("DataPrevistaDevolucao").HasColumnType("datetime2");
                b.Property<DateTime?>("DataDevolucao").HasColumnType("datetime2");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.HasKey("Id");
                b.HasIndex("LivroId");
                b.ToTable("Emprestimos");
            });

            modelBuilder.Entity("Biblioteca.Models.Livro", b =>
            {
                b.HasOne("Biblioteca.Models.Categoria", "Categoria")
                    .WithMany("Livros")
                    .HasForeignKey("CategoriaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Categoria");
            });

            modelBuilder.Entity("Biblioteca.Models.Emprestimo", b =>
            {
                b.HasOne("Biblioteca.Models.Livro", "Livro")
                    .WithMany("Emprestimos")
                    .HasForeignKey("LivroId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();
                b.Navigation("Livro");
            });

            modelBuilder.Entity("Biblioteca.Models.Categoria", b =>
            {
                b.Navigation("Livros");
            });

            modelBuilder.Entity("Biblioteca.Models.Livro", b =>
            {
                b.Navigation("Emprestimos");
            });
#pragma warning restore 612, 618
        }
    }
}
